server:
  port: 9001
spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        
        
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
    url: jdbc:mysql://semisemi.c6b0upyu6miu.ap-northeast-2.rds.amazonaws.com:3306/semisemi
    username: admin
    password: 123456789
    
    
    logging:
      level:
        root: info
        shutup.code.proj: debug
        
